name: NuviraMCGeyser
version: '${version}'

main: net.nuviramc.nuviraMCGeyser.NuviraMCGeyser
api-version: '26.2'
load: POSTWORLD

depend: ["floodgate", "PlaceholderAPI"]

authors: [ Larrox ]

commands:
  nvgeyser:
    description: "[NuviraMCGeyser] Haupt-Plugin-Befehl des Plugins NuviraMCGeyser."

  onplay:
    description: "[NuviraMCGeyser] Öffnet ein Simples Fenster für Bedrock Spieler, um die Serverliste anzusehen."
    aliases:
      - onlineplayers